# Generated by Django 3.2.2 on 2021-05-22 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundcollector',
            name='amount',
            field=models.IntegerField(default=50000),
            preserve_default=False,
        ),
    ]
