# Generated by Django 3.2.2 on 2021-05-23 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_fundcollector_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundcollector',
            name='description',
            field=models.CharField(default='covid', max_length=500),
            preserve_default=False,
        ),
    ]
