# Generated by Django 3.2.2 on 2021-05-24 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_fundcollector_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=20)),
                ('activity', models.CharField(max_length=20)),
                ('paymentmethod', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=20)),
                ('phone_no', models.IntegerField(max_length=12)),
                ('address', models.CharField(max_length=50)),
                ('amount', models.IntegerField()),
                ('date', models.DateField()),
            ],
        ),
    ]
