# Generated by Django 3.2.2 on 2021-05-24 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_donation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='phone_no',
            field=models.IntegerField(),
        ),
    ]
