# Generated by Django 3.2.2 on 2021-05-25 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_donation_phone_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='userId',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
